eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;init=create schema if not exists MCDBO
    username: sa
    password:
    driverClassName: org.h2.Driver
service:
  creditCard: '//credit-card-service/v1/creditCards/'